services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Maps the local data folder to the container
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
